name: Run Cypress Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:          # Runs the 2nd method (test) every 2 minutes if configured
    - cron: '*/2 * * * *' # Adjust for your requirement; GitHub Actions has a minimum interval of 5 minutes

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the first Cypress test
      - name: Run "Launch the Application" test
        run: npx cypress run --spec "cypress/e2e/Tooltip_Latest_Code.cy.js" --env onlyFirstTest=true

      # Step 5: Conditional logic to retry the second test
      - name: Run "Filter Records" test if the first succeeds
        run: |
          if [ $? -eq 0 ]; then
            npx cypress run --spec "cypress/e2e/Tooltip_Latest_Code.cy.js" --env onlySecondTest=true || exit 1
          fi
