name: Run Cypress Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:          # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the first Cypress test
      - name: Run "Launch the Application" test
        id: first_test
        run: npx cypress run --spec "cypress/e2e/Tooltip_Latest_Code.cy.js" --env onlyFirstTest=true

      # Step 5: Run the second Cypress test if the first succeeds
      - name: Run "Filter Records" test
        if: success() # This ensures the step runs only if the previous step succeeded
        run: npx cypress run --spec "cypress/e2e/Tooltip_Latest_Code.cy.js" --env onlySecondTest=true
