name: Run Cypress Test Every 10 Minutes with Electron & Mocha Report

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress test in Electron with mochawesome
        run: npx cypress run --spec "cypress/e2e/Nested_Frames_Handling.cy.js" --browser electron

      - name: Upload Mocha Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/
