name: Run Cypress Test Every 10 Minutes with Electron & Mocha Report

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository manually
        run: git clone https://github.com/RaamLakshmanRavuri/Cypress_Mocha_Framework.git

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Run Cypress test in Electron with mochawesome
        run: npx cypress run --spec "cypress/e2e/Nested_Frames_Handling.cy.js" --browser electron

      - name: Upload Mocha Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/
